// UVG Universal Gearhouse - Centralized Equipment Registry
const GEAR_ITEMS = [
  {
    "id": 1,
    "title": "135MM T2 2 ROKINON",
    "brand": "Rokinon",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 3200,
    "image": "images/135mm-t2-2-rokinon-prime.jpg",
    "description": "Professional Prime Lenses equipment: 135MM T2 2 ROKINON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 2,
    "title": "135MM T2 2 XEEN CINE",
    "brand": "Xeen",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/135mm-t2-2-xeen-cine-prime.jpg",
    "description": "Professional Prime Lenses equipment: 135MM T2 2 XEEN CINE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 3,
    "title": "14MM T3 1 ROKINON",
    "brand": "Rokinon",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 3200,
    "image": "images/14mm-t3-1-rokinon-prime-lenses.webp",
    "description": "Professional Prime Lenses equipment: 14MM T3 1 ROKINON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 4,
    "title": "14MM T3 1 XEEN CINE",
    "brand": "Xeen",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/14mm-t3-1-xeen-cine-prime.jpg",
    "description": "Professional Prime Lenses equipment: 14MM T3 1 XEEN CINE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 5,
    "title": "16 35MM F2 8 CANON EF MKII",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/16-35mm-f2-8-canon-ef-mkii-zoom-lenses.jpg",
    "description": "Professional Zoom Lenses equipment: 16 35MM F2 8 CANON EF MKII. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 6,
    "title": "20 INCH C STAND",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 1200,
    "image": "images/20-inch-c-stand-gearstand.webp",
    "description": "Professional Gear Stands equipment: 20 INCH C STAND. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 7,
    "title": "24 105MM F4 CANON",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/24-105mm-f4-canon-zoom-zoom-lense.jpg",
    "description": "Professional Zoom Lenses equipment: 24 105MM F4 CANON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 8,
    "title": "24 70MM F3 8 CANON",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/24-70mm-f3-8-canon-zoom-zoom.webp",
    "description": "Professional Zoom Lenses equipment: 24 70MM F3 8 CANON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 9,
    "title": "24MM T1 5 ROKINON",
    "brand": "Rokinon",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 3200,
    "image": "images/24mm-t1-5-rokinon-prime-lenses.jpg",
    "description": "Professional Prime Lenses equipment: 24MM T1 5 ROKINON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 10,
    "title": "24MM T1 5 XEEN CINE",
    "brand": "Xeen",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/24mm-t1-5-xeen-cine-prime.webp",
    "description": "Professional Prime Lenses equipment: 24MM T1 5 XEEN CINE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 11,
    "title": "35MM T1 5 ROKINON",
    "brand": "Rokinon",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 3200,
    "image": "images/35mm-t1-5-rokinon-prime.webp",
    "description": "Professional Prime Lenses equipment: 35MM T1 5 ROKINON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 12,
    "title": "35MM T1 5 XEEN CINE",
    "brand": "Xeen",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/35mm-t1-5-xeen-cine-prime.webp",
    "description": "Professional Prime Lenses equipment: 35MM T1 5 XEEN CINE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 13,
    "title": "40 INCH C STAND",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 1200,
    "image": "images/40-inch-c-stand-gearstand.webp",
    "description": "Professional Gear Stands equipment: 40 INCH C STAND. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 14,
    "title": "50MM T1 5 ROKINON",
    "brand": "Rokinon",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 3200,
    "image": "images/50mm-t1-5-rokinon-prime.jpg",
    "description": "Professional Prime Lenses equipment: 50MM T1 5 ROKINON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 15,
    "title": "50MM T1 5 XEEN CINE",
    "brand": "Xeen",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/50mm-t1-5-xeen-cine-prime.jpg",
    "description": "Professional Prime Lenses equipment: 50MM T1 5 XEEN CINE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 16,
    "title": "70 299MM F3 8 CANON",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/70-299mm-f3-8-canon-zoom-zoom.png",
    "description": "Professional Zoom Lenses equipment: 70 299MM F3 8 CANON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 17,
    "title": "85MM T1 5 ROKINON",
    "brand": "Rokinon",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 3200,
    "image": "images/85mm-t1-5-rokinon-prime.jpeg",
    "description": "Professional Prime Lenses equipment: 85MM T1 5 ROKINON. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 18,
    "title": "85MM T1 5 XEEN CINE",
    "brand": "Xeen",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/85mm-t1-5-xeen-cine-prime.webp",
    "description": "Professional Prime Lenses equipment: 85MM T1 5 XEEN CINE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 19,
    "title": "ALEXA 35",
    "brand": "Arri",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 35000,
    "image": "images/alexa-35.jpg",
    "description": "Professional Digital Cameras equipment: ALEXA 35. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 20,
    "title": "ALEXA MINI",
    "brand": "Arri",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 22000,
    "image": "images/alexa-mini-cameras.webp",
    "description": "Professional Digital Cameras equipment: ALEXA MINI. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 21,
    "title": "ALEXA MINI LF",
    "brand": "Arri",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 28000,
    "image": "images/alexa-mini-lf-cameras.jpg",
    "description": "Professional Digital Cameras equipment: ALEXA MINI LF. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 22,
    "title": "AMARAN F21C",
    "brand": "Amaran",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/amaran-f21c-lighting.webp",
    "description": "Professional Gear Lighting equipment: AMARAN F21C. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 23,
    "title": "AMARAN F22",
    "brand": "Amaran",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/amaran-f22-lighting.webp",
    "description": "Professional Gear Lighting equipment: AMARAN F22. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 24,
    "title": "AMARAN F22C",
    "brand": "Amaran",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/amaran-f22c-lighting.jpg",
    "description": "Professional Gear Lighting equipment: AMARAN F22C. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 25,
    "title": "ANGENIEUX OPTIMO PLS",
    "brand": "Universal",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/angenieux-optimo-pl-primes-lenses.webp",
    "description": "Professional Prime Lenses equipment: ANGENIEUX OPTIMO PLS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 26,
    "title": "APERTURE 300D PRO",
    "brand": "Aputure",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 4500,
    "image": "images/aperture-300d-pro-lighting.webp",
    "description": "Professional Gear Lighting equipment: APERTURE 300D PRO. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 27,
    "title": "APERTURE 80C",
    "brand": "Aputure",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/aperture-80c-lighting.jpg",
    "description": "Professional Gear Lighting equipment: APERTURE 80C. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 28,
    "title": "APERTURE LIGHT 600C",
    "brand": "Aputure",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 6500,
    "image": "images/aperture-light-600c-lighting.webp",
    "description": "Professional Gear Lighting equipment: APERTURE LIGHT 600C. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 29,
    "title": "APERTURE MC PRO KIT",
    "brand": "Aputure",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/aperture-mc-pro-kit-lighting.jpg",
    "description": "Professional Gear Lighting equipment: APERTURE MC PRO KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 30,
    "title": "APUTURE 1200D PRO",
    "brand": "Aputure",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 9800,
    "image": "images/aputure-1200d-pro-lighting.jpg",
    "description": "Professional Gear Lighting equipment: APUTURE 1200D PRO. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 31,
    "title": "APUTURE AMARAN 200D",
    "brand": "Aputure",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/aputure-amaran-200d-lighting.webp",
    "description": "Professional Gear Lighting equipment: APUTURE AMARAN 200D. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 32,
    "title": "APUTURE AMARAN 60X S",
    "brand": "Aputure",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/aputure-amaran-60x-s-lighting.jpg",
    "description": "Professional Gear Lighting equipment: APUTURE AMARAN 60X S. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 33,
    "title": "BLACKMAGIC ATEM TV STUDIO HD PRO VISION",
    "brand": "Blackmagic Design",
    "category": "Grips",
    "subcategory": "Streaming Units",
    "type": "streaming",
    "price": 5500,
    "image": "images/blackmagic-atem-tv-studio-hd-pro-vision-streaming-unit.jpg",
    "description": "Professional Streaming Units equipment: BLACKMAGIC ATEM TV STUDIO HD PRO VISION. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 34,
    "title": "BLACKMAGIC DESIGN ATEM TV STUDIO HD VISION",
    "brand": "Blackmagic Design",
    "category": "Grips",
    "subcategory": "Streaming Units",
    "type": "streaming",
    "price": 1200,
    "image": "images/blackmagic-design-atem-tv-studio-hd-vision-streaming-unit.jpeg",
    "description": "Professional Streaming Units equipment: BLACKMAGIC DESIGN ATEM TV STUDIO HD VISION. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 35,
    "title": "BLACKMAGIC WEB PRESENTERS",
    "brand": "Blackmagic Design",
    "category": "Grips",
    "subcategory": "Streaming Units",
    "type": "streaming",
    "price": 1200,
    "image": "images/blackmagic-web-presenter-streaming-units.webp",
    "description": "Professional Streaming Units equipment: BLACKMAGIC WEB PRESENTERS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 36,
    "title": "CAMGEAR V10 TRIPOD",
    "brand": "Pro Grip / Tripods",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 850,
    "image": "images/camgear-v10-tripod-gearstand.jpg",
    "description": "Professional Gear Stands equipment: CAMGEAR V10 TRIPOD. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 37,
    "title": "CANON 5D MKIV CAMERA KIT",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "DSLR Cameras",
    "type": "dslr",
    "price": 3500,
    "image": "images/canon-5d-mkiv-camera-kit-dslr.webp",
    "description": "Professional DSLR Cameras equipment: CANON 5D MKIV CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 38,
    "title": "CANON EOS 5D MK3 CAMERA KIT",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "DSLR Cameras",
    "type": "dslr",
    "price": 1200,
    "image": "images/canon-eos-5d-mk3-camera-kit-dslr.webp",
    "description": "Professional DSLR Cameras equipment: CANON EOS 5D MK3 CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 39,
    "title": "CANON H 21 KLL HD CINE STYLE",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/canon-h-21-kll-hd-cine-style-zoom-zoom-lense.webp",
    "description": "Professional Zoom Lenses equipment: CANON H 21 KLL HD CINE STYLE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 40,
    "title": "CANON HJ 11 KLL HD CINE STYLE",
    "brand": "Canon",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/canon-hj-11-kll-hd-cine-style-zoom-zoom.jpg",
    "description": "Professional Zoom Lenses equipment: CANON HJ 11 KLL HD CINE STYLE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 41,
    "title": "CARTON HEAD MAXIMA 5 0",
    "brand": "Pro Grip / Tripods",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 1200,
    "image": "images/carton-head-maxima-5-0-grips.jpg",
    "description": "Professional Gear Grips equipment: CARTON HEAD MAXIMA 5 0. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 42,
    "title": "COMBO TRIPLE LIFT",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 1200,
    "image": "images/combo-triple-lift-gearstand.jpg",
    "description": "Professional Gear Stands equipment: COMBO TRIPLE LIFT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 43,
    "title": "CRANK O VATAR 4 SECTIO1N5",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 1200,
    "image": "images/crank-o-vatar-4-sectio1n5-gearstand.png",
    "description": "Professional Gear Stands equipment: CRANK O VATAR 4 SECTIO1N5. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 44,
    "title": "CREAMSOURCE VORTEX",
    "brand": "Creamsource",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 6500,
    "image": "images/creamsource-vortex-lighting.webp",
    "description": "Professional Gear Lighting equipment: CREAMSOURCE VORTEX. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 45,
    "title": "CURVE TRACKS",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 1200,
    "image": "images/curve-tracks-grips.jpg",
    "description": "Professional Gear Grips equipment: CURVE TRACKS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 46,
    "title": "DATA VIDEO PTC 150 HD PTZ VIDEO CAM",
    "brand": "Universal",
    "category": "Cameras",
    "subcategory": "Remote Cameras",
    "type": "remote",
    "price": 1200,
    "image": "images/data-video-ptc-150-hd-ptz-video-cam-remote.jpeg",
    "description": "Professional Remote Cameras equipment: DATA VIDEO PTC 150 HD PTZ VIDEO CAM. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 47,
    "title": "DATA VIDEO PTZ CAMERA CONTRO UNIT",
    "brand": "Universal",
    "category": "Cameras",
    "subcategory": "Remote Cameras",
    "type": "remote",
    "price": 1200,
    "image": "images/data-video-ptz-camera-contro-unit-remote-cam.jpg",
    "description": "Professional Remote Cameras equipment: DATA VIDEO PTZ CAMERA CONTRO UNIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 48,
    "title": "DZO FILM CATTA ACE FF 18 35MM LENS",
    "brand": "DZO Film",
    "category": "Cameras",
    "subcategory": "Lenses",
    "type": "lenses",
    "price": 6500,
    "image": "images/dzo-film-catta-ace-ff-18-35mm-lens-lenses.jpg",
    "description": "Professional Lenses equipment: DZO FILM CATTA ACE FF 18 35MM LENS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 49,
    "title": "DZO FILM CATTA ACE FF 35 80MM LENS",
    "brand": "DZO Film",
    "category": "Cameras",
    "subcategory": "Lenses",
    "type": "lenses",
    "price": 6500,
    "image": "images/dzo-film-catta-ace-ff-35-80mm-lens-lenses.jpg",
    "description": "Professional Lenses equipment: DZO FILM CATTA ACE FF 35 80MM LENS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 50,
    "title": "DZO FILM CATTA ACE FF 70 135MM LENS",
    "brand": "DZO Film",
    "category": "Cameras",
    "subcategory": "Lenses",
    "type": "lenses",
    "price": 6500,
    "image": "images/dzo-film-catta-ace-ff-70-135mm-lens-lenses.jpg",
    "description": "Professional Lenses equipment: DZO FILM CATTA ACE FF 70 135MM LENS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 51,
    "title": "DZO",
    "brand": "DZO Film",
    "category": "Cameras",
    "subcategory": "Lenses",
    "type": "lenses",
    "price": 1200,
    "image": "images/dzo-lenses-lenses.jpg",
    "description": "Professional Lenses equipment: DZO. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 52,
    "title": "ELECTRO STORM CS15",
    "brand": "Universal",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 9800,
    "image": "images/electro-storm-cs15-lighting.jpg",
    "description": "Professional Gear Lighting equipment: ELECTRO STORM CS15. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 53,
    "title": "FALCON EYE RX 120TDX",
    "brand": "Universal",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/falcon-eye-rx-120tdx-lighting.webp",
    "description": "Professional Gear Lighting equipment: FALCON EYE RX 120TDX. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 54,
    "title": "FS7 METABONES",
    "brand": "Universal",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 1200,
    "image": "images/fs7-metabones-cameras.jpg",
    "description": "Professional Digital Cameras equipment: FS7 METABONES. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 55,
    "title": "FS7 PRO SUPPORT KIT",
    "brand": "Universal",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 1200,
    "image": "images/fs7-pro-support-kit-grips.jpg",
    "description": "Professional Digital Cameras equipment: FS7 PRO SUPPORT KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 56,
    "title": "GIRAFFE CRANE",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 2500,
    "image": "images/giraffe-crane-grips.png",
    "description": "Professional Gear Grips equipment: GIRAFFE CRANE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 57,
    "title": "HANDHELD BLUE MODULAR",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Accessories",
    "type": "accessories",
    "price": 1200,
    "image": "images/handheld-blue-modular-accessories.webp",
    "description": "Professional Accessories equipment: HANDHELD BLUE MODULAR. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 58,
    "title": "HIGH ROLLER STAND",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 1200,
    "image": "images/high-roller-stand-gearstand.jpg",
    "description": "Professional Gear Stands equipment: HIGH ROLLER STAND. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 59,
    "title": "LAOWA 24MM PROBE 35 DEGREE VIEW LENS",
    "brand": "Laowa",
    "category": "Cameras",
    "subcategory": "Lenses",
    "type": "lenses",
    "price": 1200,
    "image": "images/laowa-24mm-probe-35-degree-view-lens-lenses.webp",
    "description": "Professional Lenses equipment: LAOWA 24MM PROBE 35 DEGREE VIEW LENS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 60,
    "title": "LAOWA RANGER 28 75MM",
    "brand": "Laowa",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 6500,
    "image": "images/laowa-ranger-28-75mm-zoom-lenses.jpg",
    "description": "Professional Zoom Lenses equipment: LAOWA RANGER 28 75MM. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 61,
    "title": "LED ASTERA HELIOS KIT",
    "brand": "Astera",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 3200,
    "image": "images/led-astera-helios-kit-lighting.webp",
    "description": "Professional Gear Lighting equipment: LED ASTERA HELIOS KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 62,
    "title": "LED ASTERA TITAN KIT GEAR",
    "brand": "Astera",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 3200,
    "image": "images/led-astera-titan-kit-gear-lighting.webp",
    "description": "Professional Gear Lighting equipment: LED ASTERA TITAN KIT GEAR. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 63,
    "title": "LITEMAT L2",
    "brand": "Universal",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/litemat-l2-lighting.png",
    "description": "Professional Gear Lighting equipment: LITEMAT L2. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 64,
    "title": "LMB25",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Accessories",
    "type": "accessories",
    "price": 1200,
    "image": "images/lmb25-accessories.jpg",
    "description": "Professional Accessories equipment: LMB25. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 65,
    "title": "M18 SERIES LIGHT",
    "brand": "Universal",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 4500,
    "image": "images/m18-series-light-lighting.jpg",
    "description": "Professional Gear Lighting equipment: M18 SERIES LIGHT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 66,
    "title": "NANLITE 500B",
    "brand": "Nanlite",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 4500,
    "image": "images/nanlite-500b-lighting.jpeg",
    "description": "Professional Gear Lighting equipment: NANLITE 500B. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 67,
    "title": "NANLITE MIXPANEL 150",
    "brand": "Nanlite",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 1200,
    "image": "images/nanlite-mixpanel-150-lighting.webp",
    "description": "Professional Gear Lighting equipment: NANLITE MIXPANEL 150. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 68,
    "title": "NUCLUES M FULL KIT",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Accessories",
    "type": "accessories",
    "price": 1200,
    "image": "images/nuclues-m-full-kit-accessories.webp",
    "description": "Professional Accessories equipment: NUCLUES M FULL KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 69,
    "title": "OCONNOR HEAD 25 75",
    "brand": "Pro Grip / Tripods",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 1200,
    "image": "images/oconnor-head-25-75-grips.jpg",
    "description": "Professional Gear Grips equipment: OCONNOR HEAD 25 75. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 70,
    "title": "PAVOTUBES 2FT KIT",
    "brand": "Nanlite",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 3200,
    "image": "images/pavotubes-2ft-kit-lighting.webp",
    "description": "Professional Gear Lighting equipment: PAVOTUBES 2FT KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 71,
    "title": "PAVOTUBES 4FT KIT",
    "brand": "Nanlite",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 3200,
    "image": "images/pavotubes-4ft-kit-lighting.jpg",
    "description": "Professional Gear Lighting equipment: PAVOTUBES 4FT KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 72,
    "title": "PRO AIM CRANE",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 2500,
    "image": "images/pro-aim-crane-grips.webp",
    "description": "Professional Gear Grips equipment: PRO AIM CRANE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 73,
    "title": "RAIN COVER RODE NTG3",
    "brand": "Rode",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1500,
    "image": "images/rain-cover-rode-ntg3-sound.webp",
    "description": "Professional Sound Mixers equipment: RAIN COVER RODE NTG3. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 74,
    "title": "RODE BOOMPOLE PRO CARBON FIBRE 3M",
    "brand": "Rode",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1500,
    "image": "images/rode-boompole-pro-carbon-fibre-3m-sound.jpg",
    "description": "Professional Sound Mixers equipment: RODE BOOMPOLE PRO CARBON FIBRE 3M. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 75,
    "title": "RODE NTG3 SHOTGUN MICROPHONE",
    "brand": "Rode",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1500,
    "image": "images/rode-ntg3-shotgun-microphone-sound.webp",
    "description": "Professional Sound Mixers equipment: RODE NTG3 SHOTGUN MICROPHONE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 76,
    "title": "RONFORD SLIDER 3FT",
    "brand": "Pro Grip / Tripods",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 2500,
    "image": "images/ronford-slider-3ft-grips.jpg",
    "description": "Professional Gear Grips equipment: RONFORD SLIDER 3FT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 77,
    "title": "RONFORD SLIDER 4FT",
    "brand": "Pro Grip / Tripods",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 2500,
    "image": "images/ronford-slider-4ft-grips.jpg",
    "description": "Professional Gear Grips equipment: RONFORD SLIDER 4FT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 78,
    "title": "RONFORD SLIDER 6FT",
    "brand": "Pro Grip / Tripods",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 2500,
    "image": "images/ronford-slider-6ft-grips.jpg",
    "description": "Professional Gear Grips equipment: RONFORD SLIDER 6FT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 79,
    "title": "SECCED V15 TRIPOD",
    "brand": "Pro Grip / Tripods",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 850,
    "image": "images/secced-v15-tripod-gear-stand.jpg",
    "description": "Professional Gear Stands equipment: SECCED V15 TRIPOD. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 80,
    "title": "SENNHEISER D202 HEADPHONE",
    "brand": "Sennheiser",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1500,
    "image": "images/sennheiser-d202-headphone-sound.jpg",
    "description": "Professional Sound Mixers equipment: SENNHEISER D202 HEADPHONE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 81,
    "title": "SENNHEISER EW112P G4 RADIO LAPEL KIT",
    "brand": "Sennheiser",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1500,
    "image": "images/sennheiser-ew112p-g4-radio-lapel-kit-sound.gif",
    "description": "Professional Sound Mixers equipment: SENNHEISER EW112P G4 RADIO LAPEL KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 82,
    "title": "SENNHEISER ME66 RIFLE MICROPHONE",
    "brand": "Sennheiser",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1500,
    "image": "images/sennheiser-me66-rifle-microphone-sound.webp",
    "description": "Professional Sound Mixers equipment: SENNHEISER ME66 RIFLE MICROPHONE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 83,
    "title": "SENNHEISER RIFLE MICROPHONE",
    "brand": "Sennheiser",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1500,
    "image": "images/sennheiser-rifle-microphone-sound.webp",
    "description": "Professional Sound Mixers equipment: SENNHEISER RIFLE MICROPHONE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 84,
    "title": "SIGMA",
    "brand": "Sigma",
    "category": "Cameras",
    "subcategory": "Lenses",
    "type": "lenses",
    "price": 1200,
    "image": "images/sigma-lenses-lenses.jpg",
    "description": "Professional Lenses equipment: SIGMA. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 85,
    "title": "SKYPANEL S60",
    "brand": "Universal",
    "category": "Lighting",
    "subcategory": "Gear Lighting",
    "type": "lighting",
    "price": 6500,
    "image": "images/skypanel-s60-lighting.webp",
    "description": "Professional Gear Lighting equipment: SKYPANEL S60. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 86,
    "title": "SONY A7R MK3 CAMERA KIT",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "DSLR Cameras",
    "type": "dslr",
    "price": 4200,
    "image": "images/sony-a7r-mk3-camera-kit-dslr.jpg",
    "description": "Professional DSLR Cameras equipment: SONY A7R MK3 CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 87,
    "title": "SONY A7S II CAMERA KIT",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "DSLR Cameras",
    "type": "dslr",
    "price": 4200,
    "image": "images/sony-a7s-ii-camera-kit-dslr.jpg",
    "description": "Professional DSLR Cameras equipment: SONY A7S II CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 88,
    "title": "SONY EX3 CAMERA KIT",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 1200,
    "image": "images/sony-ex3-camera-kit-cameras.jpg",
    "description": "Professional Digital Cameras equipment: SONY EX3 CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 89,
    "title": "SONY F55 CAMERA KIT",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 18000,
    "image": "images/sony-f55-camera-kit-cameras.webp",
    "description": "Professional Digital Cameras equipment: SONY F55 CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 90,
    "title": "SONY F55 RAW MODULE",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 18000,
    "image": "images/sony-f55-raw-module-cameras.webp",
    "description": "Professional Digital Cameras equipment: SONY F55 RAW MODULE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 91,
    "title": "SONY FS7 MK2 CAMERA KIT",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 9500,
    "image": "images/sony-fs7-mk2-camera-kit-cameras.webp",
    "description": "Professional Digital Cameras equipment: SONY FS7 MK2 CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 92,
    "title": "SONY MCS 8M 8CH HD VIDEO MIXER",
    "brand": "Sony",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1200,
    "image": "images/sony-mcs-8m-8ch-hd-video-mixer-streaming-unit.jpg",
    "description": "Professional Sound Mixers equipment: SONY MCS 8M 8CH HD VIDEO MIXER. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 93,
    "title": "SONY MCS 8M VISION MIXER KIT",
    "brand": "Sony",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1200,
    "image": "images/sony-mcs-8m-vision-mixer-kit-streamin-units.jpeg",
    "description": "Professional Sound Mixers equipment: SONY MCS 8M VISION MIXER KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 94,
    "title": "SONY NEX FS700R",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 1200,
    "image": "images/sony-nex-fs700r-cameras.jpg",
    "description": "Professional Digital Cameras equipment: SONY NEX FS700R. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 95,
    "title": "SONY PXW FS5 M2 CAMERA KIT",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 7500,
    "image": "images/sony-pxw-fs5-m2-camera-kit-cameras.webp",
    "description": "Professional Digital Cameras equipment: SONY PXW FS5 M2 CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 96,
    "title": "SONY PXW X160 CAMERA KIT",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 7500,
    "image": "images/sony-pxw-x160-camera-kit-cameras.png",
    "description": "Professional Digital Cameras equipment: SONY PXW X160 CAMERA KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 97,
    "title": "SONY PXW X180",
    "brand": "Sony",
    "category": "Cameras",
    "subcategory": "Digital Cameras",
    "type": "digital",
    "price": 7500,
    "image": "images/sony-pxw-x180-cameras.webp",
    "description": "Professional Digital Cameras equipment: SONY PXW X180. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 98,
    "title": "SOUND UWP D11 RADIO LAPEL MICROPHONE",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Sound Mixers",
    "type": "sound",
    "price": 1200,
    "image": "images/sound-uwp-d11-radio-lapel-microphone-sound.jpg",
    "description": "Professional Sound Mixers equipment: SOUND UWP D11 RADIO LAPEL MICROPHONE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 99,
    "title": "STRAIGHT TRACKS",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 1200,
    "image": "images/straight-tracks-grips.jpg",
    "description": "Professional Gear Grips equipment: STRAIGHT TRACKS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 100,
    "title": "SUPERWIND UP STAND",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Stands",
    "type": "stands",
    "price": 1200,
    "image": "images/superwind-up-stand-gearstand.webp",
    "description": "Professional Gear Stands equipment: SUPERWIND UP STAND. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 101,
    "title": "TALL AND SHORT LEG",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 1200,
    "image": "images/tall-and-short-leg-grips.jpg",
    "description": "Professional Gear Grips equipment: TALL AND SHORT LEG. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 102,
    "title": "UNIVERSAL GEARHOUSE",
    "brand": "Universal",
    "category": "Grips",
    "subcategory": "Gear Grips",
    "type": "grips",
    "price": 1200,
    "image": "images/universal-gearhouse.pdf",
    "description": "Professional Gear Grips equipment: UNIVERSAL GEARHOUSE. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 103,
    "title": "ZEISS NANO KIT",
    "brand": "Zeiss",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/zeiss-nano-prime-kit-lenses.jpg",
    "description": "Professional Prime Lenses equipment: ZEISS NANO KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 104,
    "title": "ZEISS SUPREME RADIANCE KIT",
    "brand": "Zeiss",
    "category": "Cameras",
    "subcategory": "Prime Lenses",
    "type": "prime",
    "price": 5200,
    "image": "images/zeiss-supreme-radiance-prime-kit-lenses.webp",
    "description": "Professional Prime Lenses equipment: ZEISS SUPREME RADIANCE KIT. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 105,
    "title": "ZOOM F4 4CH AUDIO MIXERRECORDER",
    "brand": "Zoom",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 2800,
    "image": "images/zoom-f4-4ch-audio-mixerrecorder-sound.webp",
    "description": "Professional Zoom Lenses equipment: ZOOM F4 4CH AUDIO MIXERRECORDER. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 106,
    "title": "ZOOM F8 8CH AUDIO MIXERRECORDER",
    "brand": "Zoom",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 2800,
    "image": "images/zoom-f8-8ch-audio-mixerrecorder-sound.avif",
    "description": "Professional Zoom Lenses equipment: ZOOM F8 8CH AUDIO MIXERRECORDER. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 107,
    "title": "ZOOM H5 AUDIO RECORDER MIXERS",
    "brand": "Zoom",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/zoom-h5-audio-recorder-sound-mixers.jpg",
    "description": "Professional Zoom Lenses equipment: ZOOM H5 AUDIO RECORDER MIXERS. High-performance broadcast and cinema grade gear."
  },
  {
    "id": 108,
    "title": "ZOOM H6 AUDIO RECORDER MIXERS",
    "brand": "Zoom",
    "category": "Cameras",
    "subcategory": "Zoom Lenses",
    "type": "zoom",
    "price": 1200,
    "image": "images/zoom-h6-audio-recorder-sound-mixers.webp",
    "description": "Professional Zoom Lenses equipment: ZOOM H6 AUDIO RECORDER MIXERS. High-performance broadcast and cinema grade gear."
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GEAR_ITEMS };
}
